dataSources:
  ds_0: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_xa_0?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    autoCommit: false
  ds_1: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3307/demo_xa_0?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    autoCommit: false

rules:
  - !SHARDING
    tables:
      t_order:
        actualDataNodes: ds_${0..1}.t_order${0..1}
        databaseStrategy:
          standard:
            shardingColumn: u_id
            shardingAlgorithmName: database_inline
        tableStrategy:
          standard:
            shardingColumn: o_id
            shardingAlgorithmName: t_order_inline
    bindingTables:
      - t_order

    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: ds_${u_id % 2}
      t_order_inline:
        type: INLINE
        props:
          algorithm-expression: t_order${o_id % 2}

props:
  sql-show: true